[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "simple_app"
version = "0.1.0"
description = "A simple Python application that prints Hello, World!"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.test.dependencies]
mypy = "==1.0"